"""remove unique from session_id

Revision ID: 4d5f273d75ec
Revises: 788eede02127
Create Date: 2025-10-06 15:25:21.782929

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d5f273d75ec'
down_revision: Union[str, Sequence[str], None] = '788eede02127'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_session_id'), table_name='users')
    op.create_index(op.f('ix_users_session_id'), 'users', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_session_id'), table_name='users')
    op.create_index(op.f('ix_users_session_id'), 'users', ['session_id'], unique=True)
    # ### end Alembic commands ###
